### ISSUE TITLE
Allow creation of basic rules

### ISSUE THREAD

**Issue by ericwb** [securesauce/precli#769]
**Is your feature request related to a problem? Please describe.**
Provide a mechanism such that users of Precaution CLI can create a basic rule using an easy-to-ease template or query language with some metadata for the rule.

**Describe the solution you'd like**
Since we support tree-sitter, we could allow a basic rule definition using a tree-sitter query. Of course, the tradeoff will be accuracy of the rule since a tree-sitter query would have no control flow or data flow analysis.

The assignment of the rule ID would still need to be resolve in some way. 

**Describe alternatives you've considered**
The alternative is to use the current Python code base rules.

**Additional context**
https://tree-sitter.github.io/tree-sitter/using-parsers/queries/1-syntax.html
https://tree-sitter.github.io/py-tree-sitter/classes/tree_sitter.Query.html

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by ericwb** [comment]
Some potential YAML examples:

```yaml
- name: raw-sql-concat
  language: python
  query: |
    (call
      function: (attribute attribute: (identifier) @method)
      arguments: (argument_list
        (binary_operator
          left: (_) @lhs
          right: (_) @rhs)) @sql_expr)
    (#eq? @method "execute")
  message: "Building SQL using string concatenation can lead to injection."
  severity: error
  vulnerability_node: sql_expr
```

```yaml
- name: requests-no-timeout
  language: python
  query: |
    (call
      function: (attribute
                  object: (identifier) @module
                  attribute: (identifier) @method)
      arguments: (argument_list (_) @arg1 (_) @arg2?))
    (#eq? @module "requests")
    (#eq? @method "get")
    (#not-has-ancestor? (keyword_argument name: (identifier) @kw (#eq? @kw "timeout")))
  message: "requests.get should set a timeout to avoid hanging."
  severity: warning
  vulnerability_node: arg2
```

**Comment by ericwb** [comment]
```yaml
- name: requests-insecure-verify
  language: python
  query: |
    (call
      function: (attribute
                  object: (identifier) @module
                  attribute: (identifier) @method)
      arguments: (argument_list
        (keyword_argument
          name: (identifier) @kw
          value: (false) @vuln_val)))
    (#eq? @module "requests")
    (#any-of? @method "get" "post" "put" "delete" "head" "options")
    (#eq? @kw "verify")
  message: "Setting `verify=False` disables SSL certificate verification for `{method}`"
  severity: error
  vulnerability_node: vuln_val
```
